# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  img2b64_config = debug
endif
ifeq ($(config),release)
  img2b64_config = release
endif

PROJECTS := img2b64

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

img2b64:
ifneq (,$(img2b64_config))
	@echo "==== Building img2b64 ($(img2b64_config)) ===="
	@${MAKE} --no-print-directory -C . -f img2b64.make config=$(img2b64_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f img2b64.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   img2b64"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"